# grammar/regex.bnf
# ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾

(* ————————————————————————————————————————————————————————————————————————————————————————————————————————————————— *)

regex		::=	'/' <pattern> '/' <replacemenet> '/' <flags>

pattern		::=	( ( '.' | <LITERAL> | '\\' <ESC_CHAR> | <set> | <group> ) <quantifier>? )*

group		::= '(' <group_type>? <pattern> ')'
group_type	::= '?' ( ['=:!>|#'] | '<' ['=!'] | <flags> ':' )

quantifier	::= ( ['+*?'] | <range> ) '?'?
range		::= '{' <int> ( ',' ( <int> )? )? '}'

set			::=	'[' '^'? ( <NO_BRACK> ( '-' <NO_BRACK> )? )* ']'

(* ————————————————————————————————————————————————————————————————————————————————————————————————————————————————— *)

int			::=	<DIGIT>+
flags		::=	<FLAG_CHAR>*

(* ————————————————————————————————————————————————————————————————————————————————————————————————————————————————— *)

LITERAL		:r=	/[^.*#+^-$|(){}=!<\/\\\[\]]/
ESC_CHAR	:r=	/[0.*#+^-$|(){}=!<\/\\\[\]1-9A-GKNPQ-TVWXZabd-gknprstvwxz]/

FLAG_CHAR	:r= /[ADFJNRUVgimnsuwxy]/

NO_BRACK	:r= / [^\[\]] | (?<=\\)[\[\]] /

DIGIT		:r=	/[0-9]/
SPACE		:r=	/[ \t\n\v\f\r]/

ANY			:r= /./

(* ————————————————————————————————————————————————————————————————————————————————————————————————————————————————— *)
